export enum ROUTES_NAME {
  RESPONSABLE_MANAGER = "RESPONSABLE_MANAGER",
  NOTIFICATIONS = "NOTIFICATIONS",
  USER_INFO = "USER_INFO",
  PASSWORD_CHANGE = "PASSWORD_CHANGE",
  CREDITS_INFO = "CREDITS_INFO",
}
