export enum ROUTES_NAME {
  DETAILS = "DETAILS",
  MAIN_BOTTOM = "MAIN_BOTTOM",
  CLASSROOM_DETAILS = "CLASSROOM_DETAILS",
  ACTIVITY_PLAY = "ACTIVITY_PLAY",
  POST_DETAILS = "POST_DETAILS",
  TEACHER_ACTIVITY_RESULT_LISTING = "TEACHER_ACTIVITY_RESULT_LISTING",
  SETTINGS_DRAWER = "SETTINGS_DRAWER",
}
